# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  build:
    if: "contains(github.event.commits[0].message, 'web automation')"

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Cache local Maven repository
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ~/work/automation/automation
        mvn install

    - name: Test with Maven
      run: |
        cd ~/work/automation/automation
        mvn test -Dtest=automation.PestRoutes.TestRunner.Feature